version: "3.8"

services:

  api:
    build: ./api/
    command: go run main.go
    depends_on:
      - db
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    build: ./database/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db-data:
