FROM postgres:latest


# # Connect to the users database and create the users table
# RUN psql -U postgres -d mydb -c "CREATE TABLE users (id serial PRIMARY KEY, first_name text NOT NULL, last_name text NOT NULL, email text UNIQUE NOT NULL, password text NOT NULL);"
